# 覆盖 URLMapper 中的默认接口映射，方便在接口升级时无需重新编译
main_page=https://xueqiu.com
stock_main_page=https://stock.xueqiu.com/v5/stock/screener/quote/list.json
user_info_json=https://xueqiu.com/query/v1/user/show.json
user_comment_json=https://xueqiu.com/v4/statuses/user_timeline.json
comments_info_json=https://xueqiu.com/statuses/comments.json
comprehensive_page=https://xueqiu.com/hq
hu_shen_news_ref_json=https://stock.xueqiu.com/v5/news/query/list.json
stock_shareholders_json=https://stock.xueqiu.com/v5/stock/f10/cn/shareholder.json
stock_selector_json=https://stock.xueqiu.com/v5/stock/screener/screen.json
longhubang_json=https://stock.xueqiu.com/v5/stock/f10/cn/lhb.json
stock_industry_json=https://stock.xueqiu.com/v5/stock/f10/cn/company.json
cube_rebalancing_json=https://xueqiu.com/cubes/rebalancing/history.json
cube_trend_json=https://xueqiu.com/cubes/nav_daily/all.json
cubes_rank_json=https://xueqiu.com/cubes/discover/rank/cube/list.json
market_quotations_rank_json=https://stock.xueqiu.com/v5/stock/hot_rank/list.json
scope_stock_rank_json=https://stock.xueqiu.com/v5/stock/hot_rank/stock/list.json
stock_trend_json=https://stock.xueqiu.com/v5/stock/chart/kline.json
stock_json=https://stock.xueqiu.com/v5/stock/quote.json
industry_json=https://stock.xueqiu.com/v5/stock/screener/industry/list.json
netease_main_page=https://quotes.money.163.com/stock
stock_capital_flow=https://quotes.money.163.com/service/zjlx_chart.html
